### ISSUE TITLE
[Question] Any intention to implement chorus flower‘s expected model?

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/Better-End-Potato-Edition#1]
如题，有意向修复 https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/39 吗？

**Comment by Kasualix** [comment]
试了一下，感觉不像是我这种刚学 Java 一个月的菜鸡能够修的（

**Comment by Kasualix** [comment]
最近研究mixin很上头，我再试试

**Comment by Kasualix** [comment]
give up，改着改着还改出存档冻结的毛病来了
回头就把那无效的mixin删了

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Better-End-Potato-Edition/assets/110756250/469c151d-4cd1-41b8-8f64-1cd5ca5467ed)
好消息
