### ISSUE TITLE
Allow spawning in the end.

### ISSUE THREAD

**Issue by MagmaBro123** [MCTeamPotato/Better-End-Potato-Edition#11]
Has 2.9.0 removed the ability to spawn in the end, or has the option been moved somewhere that I'm not seeing?

If it has been removed, why. You could easily just fix the issues that it had. If you don't plan on re-adding this, please link a datapack that puts the player into the End, as I'm not aware of any.

**Comment by Kasualix** [comment]
It's in plan.

**Comment by Kasualix** [comment]
but i would recommend this: https://www.curseforge.com/minecraft/mc-mods/initial-spawn-dimension

**Comment by MagmaBro123** [comment]
It also seems that disabling the central island/dragon fights doesn't work, and disabling any ABYG biomes via the biomes.json will cause a crash, which has BYG-related stuff all over it.

**Comment by Kasualix** [comment]
disable betterendforge biomes via byg config?

**Comment by MagmaBro123** [comment]
I was using BetterEnd's biomes.json.

**Comment by Kasualix** [comment]
Oh i see you mean disable byg biomes in betterendforge config
I would look into it later.

**Comment by MagmaBro123** [comment]
Sorry for not being clear.

**Comment by Kasualix** [comment]
spawnInEnd is added [here](https://github.com/MCTeamPotato/Better-End-Potato-Edition/actions/runs/4523372135). And biomes.json now only contains minecraft & betterendforge biomes when generating. 
You can't disable byg biomes in betterendforge's config as byg doesn't use betterendforge's biome template. code

**Comment by Kasualix** [comment]
It seems you can simply use datapack to disable dragon fights as a dimension_type

**Comment by Kasualix** [comment]
disabling central island is a crazy option……
Even in latest betterend, it's not added (See [here](https://github.com/search?q=repo%3Aquiqueck/BetterEnd%20generateCentralIsland&type=code))

**Comment by Kasualix** [comment]
disabling the central island is a crazy option...
Even in latest betterend, it's not added https://github.com/search?q=repo%3Aquiqueck/BetterEnd%20generateCentralIsland&type=code

**Comment by Kasualix** [comment]
2.9.1 uploaded.
