### ISSUE TITLE
generateObsidianPlatform doesn't work.

### ISSUE THREAD

**Issue by MagmaBro123** [MCTeamPotato/Better-End-Potato-Edition#13]
Title.

![image](https://user-images.githubusercontent.com/51277766/231258242-9d4c18da-4f1a-415a-9c0f-93f1d87b0d4b.png)

This option is enabled, and spawning into the End (with the changeSpawn option enabled as well) doesn't create a platform for me to spawn on. I fall into the void.

Also, hasDragonFights/generateCentralIsland don't work, and are always enabled, regardless of the config option.

**Comment by Kasualix** [comment]
> Also, hasDragonFights/generateCentralIsland don't work, and are always enabled, regardless of the config option.
already removed

**Comment by MagmaBro123** [comment]
Still. The end fight shouldn't be enabled if those options aren't there.

**Comment by Kasualix** [comment]
Survey: What configuration options do you exactly need to change?
Gonna make a pure forge common toml config without useless thing for it.

**Comment by MagmaBro123** [comment]
Removing the dragon fight and exit portal, since I don't plan on using either. Currently making an End-based survival pack.

**Comment by LoganTheOverlord** [comment]
Hey Magma, can we get in contact? TheLogaaan#8019
I can help you, if you want.

**Comment by MagmaBro123** [comment]
Sent.

**Comment by Kasualix** [comment]
[Here](https://pastebin.ubuntu.com/p/3fr2KtDMdC/) I wrote a CraftTweaker script to let players spawn in the End with obsidian platform and removes the End Crystals. 
The SpawnX & SpawnY & SpawnZ can be changed casually, and players will also respawn in the End if they don't have a spawn point.
2.10.1 released, it supports removing dragon fight.
Sometimes Java really sucks for me, so I don't want to make this in betterendforge itself anymore.

**Comment by MagmaBro123** [comment]
Alright, sorry for being rude if I am.
