### ISSUE TITLE
Compat note from original fork

### ISSUE THREAD

**Issue by ColonelGerdauf** [MCTeamPotato/Better-End-Potato-Edition#14]
I am curious about how this fork handles inter-compatibility with Endergetic Expansion.

The original fork made note of having to add in a custom parameter, though it was very poorly explained.

**Comment by Kasualix** [comment]
![IMG_20230422_121746](https://user-images.githubusercontent.com/110756250/233761963-cb738f56-df0b-4c8b-805b-09657e6210dd.jpg)
Isn't this clear? Original fork curseforge desc.
This version removes this config option and related mixin.

**Comment by ColonelGerdauf** [comment]
Does that mean that this fork is incompatible with Endergetic, or rather the compatibility shim has become redundant?

I was speaking in relation to toml editing, as last I checked there wasn't a way to modify Endergetic via in game settings or Configured.

**Comment by Kasualix** [comment]
What are you thinking about? Looks like a big mistake.
1. energetic modifies the ender dragon nest (aka end portal)
2. someoneelse's betterendforge modifies it too
3. this causes incompatibility
4. "replace end portal" is an option in betterendforge's config
5. disable the option prevents the mod from modifying the end portal and make it compatible with energetic
6. my fork totally remove this option and related modification codes
