### ISSUE TITLE
Ritual not working

### ISSUE THREAD

**Issue by PierreV23** [MCTeamPotato/Better-End-Potato-Edition#15]
![image](https://user-images.githubusercontent.com/77776198/234972985-f3c9e60b-60af-460d-858d-421843be238e.png)
Dont really know what else to say, it seems to me like its a correct ritual for the Eternal Crystal.

**Comment by Kasualix** [comment]
What's on your Infusion Pedestal?
Shouldn't it be End Crystal?
And it works for me.

**Comment by PierreV23** [comment]
> What's on your Infusion Pedestal?
> Shouldn't it be End Crystal?
> And it works for me.

It is indeed a End Crystal. I am playing on the Medieval Minecraft modpack (forge 1.16.5), hence the texture pack.

Is there a specific order / orientation i have to put the pedestals in? Or maybe a specific order for placing the recipe?

**Comment by Kasualix** [comment]
Medieval Minecraft's mod version is out-dated.

**Comment by PierreV23** [comment]
> Medieval Minecraft's mod version is out-dated.

So rituals don't work in that version? I play on a server so there's not much I can do.

**Comment by Kasualix** [comment]
Maybe. 
There's not much I can do too and I can only ask you to request your server administrator to update the mod version.
