### ISSUE TITLE
 Loading chunks affected by Betterend crashes multiplayer servers.

### ISSUE THREAD

**Issue by ShortEye** [MCTeamPotato/Better-End-Potato-Edition#16]
After beating the enderdragon and attempting to use the gateway to travel to the end islands, the server crashes and soft-locks the user that used the gateway. Here's the crash report (I have tried on later versions of Betterend, but I get similar results):
[crash-2023-04-29_17.30.21-server.txt](https://github.com/MCTeamPotato/Better-End-Potato-Edition/files/11360126/crash-2023-04-29_17.30.21-server.txt)

**Comment by ShortEye** [comment]
Here's the crash report on the latest release:
[crash-2023-04-29_12.12.33-server.txt](https://github.com/MCTeamPotato/Better-End-Potato-Edition/files/11360132/crash-2023-04-29_12.12.33-server.txt)

**Comment by Kasualix** [comment]
update modernfix
