### ISSUE TITLE
一些 Tag 缺失、有问题

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/Better-End-Potato-Edition#4]
https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/38
可以参考一下 The Endergetic Expansion 的

https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/42
看了一下秋原的，似乎是 minecraft/tags/blocks 里告示牌的标签要有 standing_signs 和 wall_signs 两种，原模组里把它标成 sings 了

**Comment by Kasualix** [comment]
https://github.com/MCTeamPotato/Better-End-Potato-Edition/commit/b7b009ecf89b27c9ad3eff754006e312de92090b
这样咩

**Comment by wasdspace** [comment]
lgtm
