### ISSUE TITLE
Unknown registry element.

### ISSUE THREAD

**Issue by wasdspace** [MCTeamPotato/Better-End-Potato-Edition#5]
https://github.com/Someone-Else-Was-Taken/BetterEndForge-Reforked/issues/62
我点击创建世界后会输出这两行，不知道原 issue 是个什么情况。
```
Error adding element: Unknown registry element mod.beethoven92.betterendforge.common.world.feature.SinglePlantFeature@5f0900f8
Error adding element: Base value out of range: 256 [-10-128]
```

**Comment by Kasualix** [comment]
我也看不懂（

**Comment by Kasualix** [comment]
~回头问问ChatGPT~

**Comment by Kasualix** [comment]
找到原因了

**Comment by Kasualix** [comment]
找到原因了……
真是有点绝

**Comment by Kasualix** [comment]
https://github.com/MCTeamPotato/Better-End-Potato-Edition/commit/85b30537df38001949986d1e4df4d85c5b3d85da#diff-c9309f7c34b5be7ccc1523b0f3ebf08302173bdd64de270054cc07edd966adb4R204
应该没问题了

**Comment by wasdspace** [comment]
好像只有这一行修好了……
`Error adding element: Unknown registry element mod.beethoven92.betterendforge.common.world.feature.SinglePlantFeature@5f0900f8`
迷惑……

**Comment by Kasualix** [comment]
我这没有另一行报错

**Comment by wasdspace** [comment]
为啥我有……
点击单人游戏后出现的
`[053月2023 15:03:44.491] [Render thread/ERROR] [net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Base value out of range: 256 [-10-128]`
可能是你那边有已经创建好了的世界？在空 saves 的情况试一下，反正我这边每次从主界面点击单人游戏都会输出一行

**Comment by Kasualix** [comment]
我每次都是新建世界的（

**Comment by wasdspace** [comment]
saves 文件夹也是空的吗，假如是空的就很奇怪了

**Comment by Kasualix** [comment]
https://github.com/team-abnormals/endergetic/issues/175

**Comment by wasdspace** [comment]
被第一行误导了……
是其他模组的锅也就是说，大概率修不好了（

**Comment by Kasualix** [comment]
qs
